version: '3'

services:
  payload:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      # The volume below came with the create-payload-app command, but it is commented out.
      # Mounting node_modules as a volume can cause permission issues with pnpm and Dev Containers.
      # It's safer to let the container manage its own node_modules internally.
      # - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && pnpm install && tail -f /dev/null"
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  # See above comment about node_modules.
  # node_modules:
